const path = require("path");
const dotenv = require("dotenv");
const database = require("./config/database.js");
const express = require("express");
const bodyParser = require("body-parser");
const methodOverride = require("method-override");
const app = express();
const indexRouter = require("./routes/index.js");
const movieRoutes = require("./routes/movies.js");
const performerRoutes = require("./routes/performers.js");
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
dotenv.config({ path: "./config.env" });
app.set("view engine", "ejs");
app.set("views", "views");

app.use(methodOverride("_method"));
app.use("/", indexRouter);
app.use("/movies", movieRoutes);
app.use("/performers", performerRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("server connected on port 3000"));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, "public")));
